### ISSUE TITLE
Integrate ECharts

### ISSUE THREAD

**Issue by buremba** [jinjat-data/jinjat-refine-next#7]
* We should use [`datasets`](https://apache.github.io/echarts-handbook/en/concepts/dataset/)
* We need to use raw ECharts config rather than inventing something new

Here is an example exposure to be parsed:

```
- name: example_dashboard
    type: dashboard
    owner:
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: AutoAwesome
        parameters:
          country:
            type: string
        items:
          - width: 1
            height: 1
            left: 2
            top: 2
            chart:
              dataset:
                analysis: example_endpoint
                body:
                  country: ${country}
                query_params:
              xAxis:
                type: category
              series:
                - type: bar
```
